version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Critical linters only - catch real bugs
    - errcheck       # Unchecked errors
    - govet          # Suspicious constructs
    - staticcheck    # Static analysis bugs
    - ineffassign    # Ineffectual assignments
    - unused         # Unused code
    # gosec disabled for Phase A - will enable and fix in Phase B

  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: false  # Too noisy
    check-blank: false            # Allow _ = errors for now

  govet:
    enable-all: false
    enable:
      - atomic           # Atomic access issues
      - bools            # Boolean mistakes
      - errorsas         # errors.As usage
      - ifaceassert      # Impossible interface assertions
      - nilfunc          # Nil function comparisons
      - printf           # Printf format issues
      - stringintconv    # String/int conversions
    disable:
      - shadow           # Too many false positives
      - fieldalignment   # Style, not bugs

  staticcheck:
    checks: ["all"]

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # File inclusion via variable (false positives in tests)
      - G306  # File permissions (too strict for development)

issues:
  exclude-dirs:
    - vendor
    - testdata

  exclude-files:
    - ".*\\.pb\\.go$"

  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Exclude specific gosec rules (will fix in Phase B)
    - text: "G304.*file inclusion"
      linters:
        - gosec
    - text: "G306.*file permissions"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
