version: "2"
run:
  tests: true
linters:
  enable:
    - errname
    - errorlint
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - commentFormatting
        - whyNoLint
        - unnamedResult
        - ifElseChain
        - appendCombine
        - equalFold          # Too many changes, not critical
        - emptyStringTest    # Style preference
        - octalLiteral       # 0600 is clearer than 0o600
        - sprintfQuotedString # Too pedantic
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
        - G304
      severity: medium
      confidence: medium
    govet:
      enable:
        - atomic
        - bools
        - errorsas
        - ifaceassert
        - nilfunc
        - printf
        - stringintconv
      disable:
        - shadow
        - fieldalignment
      enable-all: false
    staticcheck:
      checks:
        - all
        - -ST1003  # SqlLiteral naming is intentional (matches Ruby Arel)
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - unparam
        path: _test\.go
    paths:
      - .*\.pb\.go$
      - vendor
      - testdata
      - third_party$
      - builtin$
      - ^examples/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - ^examples/
