version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Core linters
    - errcheck       # Check for unchecked errors
    - govet          # Go vet checks
    - staticcheck    # Static analysis (includes gosimple)
    - unused         # Unused code detection

    # Quality linters
    - ineffassign    # Detect ineffectual assignments
    - gocritic       # Comprehensive Go source code linter
    - misspell       # Spelling mistakes
    - unconvert      # Unnecessary type conversions
    - unparam        # Unused function parameters

    # Error handling
    - errname        # Error names should end with Error
    - errorlint      # Error wrapping best practices

    # Security
    - gosec          # Security problems

  disable-all: false

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - errorsas
      - ifaceassert
      - nilfunc
      - printf
      - stringintconv
    disable:
      - shadow
      - fieldalignment      # Too many changes, not critical

  staticcheck:
    checks: ["all"]

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Covered by errcheck
      - G304  # File inclusion via variable (false positives in tests)

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint
      - unnamedResult      # Too many changes for Phase B
      - ifElseChain        # Not critical
      - appendCombine      # Not critical

issues:
  exclude-dirs:
    - vendor
    - testdata

  exclude-files:
    - ".*\\.pb\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
        - gosec  # Exclude all gosec from tests

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
